#!/bin/bash
# Autogenerated-scenario test (default options, base image, no mise).
#
# The feature's functional work runs in onCreateCommand (provision-auth) and needs
# a real mise + the /workspace checkouts of compy and bash — neither exists in the
# features-test base image. So here we verify the *staging* contract (the helper +
# persisted config) and that provision-auth degrades gracefully when mise is
# absent. The end-to-end check (gen-jwt mints a signed .jwt) is done in the
# graphql devcontainer, which has mise.
set -e

source dev-container-features-test-lib

check "provision-auth is installed and executable" test -x /usr/local/bin/provision-auth

check "config.env persists the default compy repo path" \
    bash -c 'grep -Fq "COMPY_REPO_PATH=\"/workspace/compusib/compy\"" /usr/local/lib/features/auth/config.env'

check "config.env pins ssh-jwt v0.1.0 by default" \
    bash -c 'grep -Fq "SSH_JWT_VERSION=\"v0.1.0\"" /usr/local/lib/features/auth/config.env'

check "config.env keeps the Go toolchain by default" \
    bash -c 'grep -Fq "KEEP_GO_TOOLCHAIN=\"true\"" /usr/local/lib/features/auth/config.env'

# Without mise on PATH, provisioning must warn and exit 0 (never block attach).
check "provision-auth degrades gracefully without mise" provision-auth

reportResults
