include:
  - devcontainer-features-dev.yml
  - volumes/${COMPOSE_VOLUME_COMPUSIB:-noop}.yml
  - volumes/${COMPOSE_VOLUME_CANTECORP:-noop}.yml
  - volumes/${COMPOSE_VOLUME_COMBINED:-noop}.yml
  - volumes/${COMPOSE_VOLUME_HOME:-noop}.yml
name: "${STACK_NAME:-${DEV_STACK_NAME:-stack}}"
networks:
  stack:
    name: "${STACK_NAME:-${DEV_STACK_NAME:-stack}}"
  gateway:
    external: true
